language: node_js
script: 
  - echo ${TRAVIS_TEST}
  - echo ${PWD_TEST}
  - echo ${UNAME_TEST}
  - echo ${TRAVIS_NODE_VERSION}
after_success: "curl -T sample.txt -u ${UNAME_TEST}:${PWD_TEST} ftp://77.104.152.175/public_html/"